version: '3'
services:
    db:
        build: ./database
        stdin_open: true
        tty: true
        ports:
        - 5000:5000
        volumes:
        - ./database:/code
        environment:
            FLASK_ENV: development
    ml:
        build: ./ml_service
        ports:
        - 8000:8000
        volumes:
        - ./ml_service:/code
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 0